# docker-compose.yml

version: '3'

services:
  opcua-server:
    build:
      context: ..
      dockerfile: deploy/image/Dockerfile
    image: opcua-server:latest
    command: python server.py
    volumes:
      - ../src:/app/opcua/server
    ports:
      - "4840:4840"
    
    restart: always


